import { IntegrationCatalogItem } from './integration.models';

export const INTEGRATION_CATALOG: IntegrationCatalogItem[] = [
  {
    key: 'slack',
    name: 'Slack',
    description: 'Team messaging and collaboration platform',
    category: 'communication',
    iconPath: 'assets/icons/integrations/slack.svg',
    brandColor: '#4A154B',
    isPopular: true,
    credentialFields: [
      {
        key: 'botToken',
        label: 'Bot Token',
        type: 'password',
        required: true,
        placeholder: 'xoxb-...',
      },
    ],
  },
  {
    key: 'gmail',
    name: 'Gmail',
    description: 'Email communication and inbox management',
    category: 'communication',
    iconPath: 'assets/icons/integrations/gmail.svg',
    brandColor: '#EA4335',
    isPopular: true,
    credentialFields: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Enter your Gmail API key',
      },
    ],
  },
  {
    key: 'google-calendar',
    name: 'Google Calendar',
    description: 'Schedule meetings and sync calendar events',
    category: 'calendar',
    iconPath: 'assets/icons/integrations/google-calendar.svg',
    brandColor: '#4285F4',
    isPopular: true,
    credentialFields: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Enter your Google Calendar API key',
      },
    ],
  },
  {
    key: 'quickbooks',
    name: 'QuickBooks',
    description: 'Accounting, invoicing, and financial management',
    category: 'accounting',
    iconPath: 'assets/icons/integrations/quickbooks.svg',
    brandColor: '#2CA01C',
    isPopular: false,
    credentialFields: [
      {
        key: 'clientId',
        label: 'Client ID',
        type: 'text',
        required: true,
        placeholder: 'Enter your Client ID',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        required: true,
        placeholder: 'Enter your Client Secret',
      },
    ],
  },
  {
    key: 'mailchimp',
    name: 'Mailchimp',
    description: 'Email marketing campaigns and audience management',
    category: 'marketing',
    iconPath: 'assets/icons/integrations/mailchimp.svg',
    brandColor: '#FFE01B',
    isPopular: true,
    credentialFields: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Enter your Mailchimp API key',
      },
    ],
  },
  {
    key: 'dropbox',
    name: 'Dropbox',
    description: 'Cloud file storage and document sharing',
    category: 'storage',
    iconPath: 'assets/icons/integrations/dropbox.svg',
    brandColor: '#0061FF',
    isPopular: false,
    credentialFields: [
      {
        key: 'accessToken',
        label: 'Access Token',
        type: 'password',
        required: true,
        placeholder: 'Enter your Dropbox access token',
      },
    ],
  },
  {
    key: 'github',
    name: 'GitHub',
    description: 'Source code hosting and project management',
    category: 'developer-tools',
    iconPath: 'assets/icons/integrations/github.svg',
    brandColor: '#181717',
    isPopular: false,
    credentialFields: [
      {
        key: 'personalAccessToken',
        label: 'Personal Access Token',
        type: 'password',
        required: true,
        placeholder: 'ghp_...',
      },
    ],
  },
  {
    key: 'zapier',
    name: 'Zapier',
    description: 'Workflow automation connecting apps and services',
    category: 'developer-tools',
    iconPath: 'assets/icons/integrations/zapier.svg',
    brandColor: '#FF4A00',
    isPopular: false,
    credentialFields: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Enter your Zapier API key',
      },
      {
        key: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://hooks.zapier.com/...',
      },
    ],
  },
  {
    key: 'hubspot',
    name: 'HubSpot',
    description: 'Inbound marketing, sales, and CRM platform',
    category: 'marketing',
    iconPath: 'assets/icons/integrations/hubspot.svg',
    brandColor: '#FF7A59',
    isPopular: false,
    credentialFields: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Enter your HubSpot API key',
      },
    ],
  },
  {
    key: 'twilio',
    name: 'Twilio',
    description: 'SMS, voice, and messaging communication APIs',
    category: 'communication',
    iconPath: 'assets/icons/integrations/twilio.svg',
    brandColor: '#F22F46',
    isPopular: false,
    credentialFields: [
      {
        key: 'accountSid',
        label: 'Account SID',
        type: 'text',
        required: true,
        placeholder: 'AC...',
      },
      {
        key: 'authToken',
        label: 'Auth Token',
        type: 'password',
        required: true,
        placeholder: 'Enter your Auth Token',
      },
    ],
  },
  {
    key: 'whatsapp',
    name: 'WhatsApp',
    description: 'Business messaging and customer communication',
    category: 'communication',
    iconPath: 'assets/icons/integrations/whatsapp.svg',
    brandColor: '#25D366',
    isPopular: true,
    credentialFields: [
      {
        key: 'businessApiToken',
        label: 'Business API Token',
        type: 'password',
        required: true,
        placeholder: 'Enter your WhatsApp Business API token',
      },
    ],
  },
  {
    key: 'instagram',
    name: 'Instagram',
    description: 'Social media engagement and direct messaging',
    category: 'communication',
    iconPath: 'assets/icons/integrations/instagram.svg',
    brandColor: '#E4405F',
    isPopular: false,
    credentialFields: [
      {
        key: 'accessToken',
        label: 'Access Token',
        type: 'password',
        required: true,
        placeholder: 'Enter your Instagram access token',
      },
    ],
  },
];
